# Generated by Django 2.2 on 2021-06-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0003_auto_20210608_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='hobby',
            new_name='hobby_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='poster',
        ),
    ]
