# Generated by Django 2.2 on 2021-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0004_auto_20210608_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
