# Generated by Django 2.2 on 2021-06-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0005_hobby_hobby_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_img',
            field=models.ImageField(default='default.png', upload_to='images/%y'),
        ),
    ]
