# Generated by Django 2.2 on 2021-06-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0007_auto_20210612_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
