# Generated by Django 2.2 on 2021-06-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0010_auto_20210612_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_img',
            field=models.ImageField(default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
