# Generated by Django 2.2 on 2021-06-13 07:10

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0011_auto_20210612_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_img',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=''),
        ),
    ]
