# Generated by Django 2.2 on 2021-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0014_auto_20210614_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
