# Generated by Django 2.2 on 2021-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0015_auto_20210615_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
