# Generated by Django 2.2 on 2021-05-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formtest', '0002_auto_20210521_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
