# Generated by Django 2.2 on 2021-05-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
