# Generated by Django 2.2 on 2021-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20210507_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.TextField(),
        ),
    ]
