# Generated by Django 2.2 on 2021-06-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20210511_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
