# Generated by Django 2.2 on 2021-04-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='release_date',
        ),
    ]
